before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - '-s -w'
      - '-X main.version={{ .Version }}'
      - '-X main.commit={{ .ShortCommit }}'

archives:
  - replacements:
      386: i386
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^test'
