name: release

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install upx-ucl
        run: sudo apt install upx-ucl -y
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
